const SET_TOKEN = "SET_TOKEN";
const SET_INTRODUCTION= "SET_INTRODUCTION";
const MULTSET_NAMEIPLY= "SET_NAME";
const SET_ROLES= "SET_ROLES";

export {SET_TOKEN,SET_INTRODUCTION,MULTSET_NAMEIPLY,SET_ROLES}

